### ISSUE TITLE
Streaming

### ISSUE THREAD

**Issue by chriskinsman** [schroffl/node-lzo#16]
I am trying to wrap this in a Transform stream as I am dealing with files that are multiple GB in size.

```
const lzo = require('lzo');
const Transform = require('stream').Transform;

class LzoTransform extends Transform {
    constructor(options) {
        options = options || {};
        super(options);
    }

    _transform(chunk, encoding, callback) {
        this.push(lzo.decompress(chunk));
        setImmediate(callback);
    }
}

const fs = require('fs');
console.info('Starting');
const readStream = fs.createReadStream('file.txt.lzo', { encoding: null });
const writeStream = fs.createWriteStream('file.txt');

writeStream.on('finish', () => {
    console.info('Finished');
    process.exit(0);
});

readStream.pipe(new LzoTransform()).pipe(writeStream);
```

Error: Decompression failed with code: LZO_E_LOOKBEHIND_OVERRUN

I suspect that this LZO library may not be able to decompress arbitrary chunks of a file and must do the whole thing at once?  Any thoughts?

Thanks!

Chris

**Comment by schroffl** [comment]
Hi Chris,

I'm kinda busy until the end of the week, but I thought I'd let you know that I took notice of your issue.

If you have full control over the side that does the compression you could write your data in chunks, which you then read and decompress separately. [Here's a StackOverflow post](https://stackoverflow.com/questions/4235019/how-to-get-lzo-to-work-with-a-file-stream/10266201) that I found on the topic.

I hope to get some research done in the next few days. I will get back to you :)

– schroffl

**Comment by chriskinsman** [comment]
Great to hear.

I have no control over the producing side.

After doing a bit more research there is talk of an LZO function that given a chunk will indicate if that chunk is complete yet. Can't remember where I saw that now.

Shocked there is so little for nodejs around lzo compression...

**Comment by schroffl** [comment]
Okay, so I just ran a few tests. If you want I can post the source for that. The program just tries to decompress the compressed data into a buffer, which is increasing in size from 1 byte up, until it is able to get some data out.
The size of the output buffer is the `counter: x` in the dump below.

```
user@device ~/minilzo-2.10> gcc minilzo.c test.c && ./a.out
Initial Data: "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxy"
compress_result: OK
compressed size: 50


---------------------------------------------
counter: 25
dec_len: 25
decompress_safe result: OUTPUT_OVERRUN

Decompressed so far: "abcdefghijklmnopqrstuvwxy"

---------------------------------------------
counter: 85
dec_len: 85
decompress_safe result: OUTPUT_OVERRUN

Decompressed so far: "abcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxyabcdefghijklmnopqrstuvwxyabcdefghij"
```

As you can see, `lzo1x_decompress_safe` is eventually able to decompress some of the data (with an output buffer of 25 bytes and 85 bytes – and the final size of 100 bytes, of course).
_(**EDIT:** Apparently this depends on the compressed data anyways. It could very well be that it's not able to decompress anything until the very end...)_

This looks rather promising. Now we just need to know if we can truncate some of the _compressed_ data at the beginning and feed that back into `lzo1x_decompress_safe` until we get the next chunk.

However, this is where I don't know how to continue. How many bytes are we supposed to remove at the beginning? We can't just truncate `dec_len` bytes, because that corresponds to the uncompressed data, not the compressed one.

Do you have any thoughts on this?

**Comment by schroffl** [comment]
So I just tested compressing a 10Gb file with the `lzop` command line tool. Since that worked fine I assume that there is a way to do this. I'm gonna look through the source code to see if I find anything that helps.

**Comment by chriskinsman** [comment]
That was how I ended up getting something to work, i.e. ```lzop```

Basically did this:

```
const readStream = fs.createReadStream('foo.txt.lzo', {encoding: null} );
const writeStream = fs.createWriteStream('foo.txt');

const child = childProcess.spawn('lzop', ['-d'], { shell: true, stdio: 'pipe' });

writeStream.on('finish', () => {
   console.info('Finished');
   process.exit(0);
});

lzop.stdout.pipe(writeStream);
readStream.pipe(lzop.stdin);
```

Except in my case the read stream was coming from S3 and the write stream was going back to S3.

**Comment by schroffl** [comment]
So apparently the `lzop` tool does indeed split the data into chunks (or blocks, as it's called in the code) of 64MB and compresses them. I'm not sure what to make of this... What do you think?

**Comment by chriskinsman** [comment]
It also has some headers and other things it looks like it prepends to the
file...

I think it would be cool to have something like this as a stream but I at
least have found an alternative for the moment!
