### ISSUE TITLE
How to find lzo.node binding file??

### ISSUE THREAD

**Issue by afenderson** [schroffl/node-lzo#2]
Hi, I installed this with a simple npm install and followed the example, but even if I print the version it fails with this error:
`/home/centos/telemetry/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/centos/telemetry/node_modules/lzo/build/node_lzo.node
 → /home/centos/telemetry/node_modules/lzo/build/Debug/node_lzo.node
 → /home/centos/telemetry/node_modules/lzo/build/Release/node_lzo.node
 → /home/centos/telemetry/node_modules/lzo/out/Debug/node_lzo.node
 → /home/centos/telemetry/node_modules/lzo/Debug/node_lzo.node
 → /home/centos/telemetry/node_modules/lzo/out/Release/node_lzo.node
 → /home/centos/telemetry/node_modules/lzo/Release/node_lzo.node
 → /home/centos/telemetry/node_modules/lzo/build/default/node_lzo.node
 → /home/centos/telemetry/node_modules/lzo/compiled/7.10.0/linux/x64/node_lzo.node
    at bindings (/home/centos/telemetry/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/centos/telemetry/node_modules/lzo/index.js:3:32)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/centos/telemetry/new_hdfstest.js:1:75)`

is a **node_lzo.node** file supposed to be created or do I have to manually create one? 

FWIW, when I try it here, just clicking Run gives the same error:
https://npm.runkit.com/lzo

Thanks,
Chris

**Comment by afenderson** [comment]
Never mind, bindings npm package needed to be installed. Should be included as a dependency. 

Chris

**Comment by schroffl** [comment]
But it is [listed as a dependency](https://github.com/schroffl/node-lzo/blob/master/package.json#L17) and the error is coming from [this line](https://github.com/schroffl/node-lzo/blob/master/index.js#L3) in the `index.js` of my package. I don't know why, but it seems like it can't find the bindings file. Either am I missing something or it's a bug in the bindings package. And to me the former seems a lot more likely. If you know how to fix it please let me know.

**Comment by NiketanMhatre** [comment]
Hello @schroffl ,

I am getting `Uncaught Error: A dynamic link library (DLL) initialization routine failed.` error, in this file
"~\node_modules\lzo\node_modules\bindings\bindings.js:83".

I am trying to develop electron app on windows 10.

 I saw one comment in other issue lzo package won't run on browser, could this be reason for above error? It will be appreciable if you could tell me before going any further with this package.

**Comment by schroffl** [comment]
Hey @NiketanMhatre, 

it shouldn't be a problem to use this package with electron, since electron provides a way to run node.js code as far as I know. I tried the package on a freshly installed Windows 10 and it worked fine, so windows shouldn't be the problem either.
In your [other issue](https://github.com/schroffl/node-lzo/issues/7) it seems like the Windows Build Tools are missing. When I reinstalled Windows I had a similar problem and ultimately found this [offical microsoft page](https://www.visualstudio.com/de/downloads/). There you can scroll down until you find `Build Tools for Visual Studio 2017`. Download this, run the installer and try to build this package again.
I think the Build Tools also come shipped with the Visual Studio IDE but I didn't want to install this elephant on my slick, new Windows 10.

Playing the devils advocate however, I'd advise you against using this package for any critical applications, because you are most certainly going to encounter weird bugs and errors.
If you decide to use it anyways, feel free to create an issue when something isn't working as expected and I will address it when I have the time and knowledge to fix it.

Oh and by the way, please don't comment on an issue next time if you don't have the same problem, but rather open a new one.

Have a good day!
