### ISSUE TITLE
Browserify and fs dependency

### ISSUE THREAD

**Issue by electronut** [schroffl/node-lzo#4]
Hello,

I am trying to use this module in a cordova app using browserify, and am running into an issue with the `fs` module. This is what I am trying to do:

> $ cat lzo.js
> var LZO = require('lzo');
> console.log(LZO);
> 
> $ browserify lzo.js -o lzo-bundle.js
> 

The generated `lzo-bundle.js` has a depedency on `fs` which is causing problems during run-time. 

```
/**
 * Module dependencies.
 */

var fs = require('fs')
  , path = require('path')
  , join = path.join
  , dirname = path.dirname
  , exists = fs.existsSync || path.existsSync
```

Errors:

```
Uncaught TypeError: exists is not a function
    at Function.getRoot (lzo-bundle.js:2493)
    at bindings (lzo-bundle.js:2395)
    at Object.<anonymous> (lzo-bundle.js:2513)
    at Object.9.bindings (lzo-bundle.js:2579)
    at s (lzo-bundle.js:1)
    at lzo-bundle.js:1
    at Object.7.lzo (lzo-bundle.js:2336)
    at s (lzo-bundle.js:1)
    at e (lzo-bundle.js:1)
    at lzo-bundle.js:1

```

I'd appreciate any help in sorting this out.

Thanks!

**Comment by schroffl** [comment]
A dependency of this package, [`bindings`](https://github.com/TooTallNate/node-bindings), seems to be causing this error (See [Line 6](https://github.com/TooTallNate/node-bindings/blob/master/bindings.js#L6)).
However I don't think that you can even use this package in the browser, because it doesn't implement the algorithm in JavaScript, but only provides bindings to the native C implementation (which has to be compiled for your platform, but npm handles that on installation).
If you need lzo so desperatley you can try to use [emscripten](https://github.com/kripken/emscripten).
Sorry for not being the help you probably hoped for.

**Comment by electronut** [comment]
Thanks for the prompt reply. I'll have to look at other options...
